from __future__ import annotations

from enum import StrEnum


class AskRuntimeWarning(StrEnum):
    MODEL_USAGE_MEASUREMENT_MISSING = "MODEL_USAGE_MEASUREMENT_MISSING"
    LOCAL_USAGE_MEASUREMENT_NOT_CURRENT = "LOCAL_USAGE_MEASUREMENT_NOT_CURRENT"
    AI_TOKEN_BUDGET_ALERT_THRESHOLD_REACHED = "AI_TOKEN_BUDGET_ALERT_THRESHOLD_REACHED"
    AI_TOKEN_BUDGET_EXCEEDED_ALERT_ONLY = "AI_TOKEN_BUDGET_EXCEEDED_ALERT_ONLY"
